# Generated by Django 6.0.5 on 2026-05-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionrecord',
            old_name='created_at',
            new_name='imported_at',
        ),
        migrations.RemoveField(
            model_name='emissionrecord',
            name='status',
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='locked_for_audit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emissionrecord',
            name='original_raw_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissionrecord',
            name='source_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='source_type',
            field=models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=50),
        ),
    ]
